version: "3"
services:
  web:
    build: ./web
    image: wp_web
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - ./app/src:/var/www/html
      - ./logs/web:/var/log/nginx
  app:
    build: ./app
    image: wp_app
    restart: always
    depends_on:
      - db
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=#sample1234
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - ./app/src:/var/www/html
      - ./logs/app:/var/log/php
  db:
    build: ./db
    image: wp_db
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=#sample1234
      - MYSQL_DATABASE=wordpress
    volumes:
      - ./db/mysql_init:/docker-entrypoint-initdb.d
      - ./logs/db:/var/log/mysql