version: "3"
services:
  web:
    image: nginx:1.20-alpine
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - ./web/nginx:/etc/nginx
      - ./app/src:/var/www/html
      - ./logs/web:/var/log/nginx
  app:
    image: wordpress:5.7-php8.0-fpm-alpine
    restart: always
    depends_on:
      - db
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=#sample1234
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - ./app/src:/var/www/html
      - ./logs/app:/var/log/php
  db:
    image: mysql:8.0.25
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=#sample1234
      - MYSQL_DATABASE=wordpress
    volumes:
      - ./db/mount:/var/lib/mysql
      - ./logs/db:/var/log/mysql