version: "3"
services:
  web:
    build: ./web
    image: wp_web
    ports:
      - 80:80
    depends_on:
      - app
    environment:
      - APP_HOST: app
    volumes:
      - ./src:/var/www/html
      - ./logs/web:/var/log/nginx
  app:
    # php-fpmイメージを基にしたコンテナ
    build: ./app
    image: wp_app
    depends_on:
      - db
    environment:
      - DB_PASSWORD: #sample1234
      - DB_HOST: db
    volumes:
      - ./src:/var/www/html
      - ./logs/app:/var/log/php

#    # wordpressイメージを基にしたコンテナ 
#    build: ./app_base_wp
#    image: wp_app
#    depends_on:
#      - db
#    environment:
#      - WORDPRESS_DB_HOST: db
#      - WORDPRESS_DB_USER: root
#      - WORDPRESS_DB_PASSWORD: #sample1234
#      - WORDPRESS_DB_NAME: 
#      - WORDPRESS_TABLE_PREFIX: 
#    volumes:
#      - ./src/wp-content:/var/www/html/wp-content

  db:
    build: ./db
    image: wp_db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD: #sample1234
      - MYSQL_DATABASE: wordpress
    volumes:
      - ./db/mysql_init:/docker-entrypoint-initdb.d
      - ./logs/db:/var/log/mysql